#!/usr/bin/env python

#   // INITIAL DESCRIPTION //
"""Short Module Description; Reference To Readme"""

#   // MEATDATA // 
__author__ = 'Alina Jansen'
__date__ = '2024-09-25'

#   // IMPORTS //

#   Imports Of Existing Libraries
import datetime
import os

#   Imports From Existing Libraries 


#   // TODOS & NOTES //
#   TODO: This Is An Example To Do
#   NOTE: This Is An Example Note

#   // CLASS & METHOD DEFINITIONS //
class Output():

    '''
    This Class Handles The Output Files Generated By GMX2QMMM
    '''

    #   // INIT //
    def __init__(self) -> None:
        '''
        ------------------------------ \\
        EFFECT: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        INPUT: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        RETURN: \\
        --------------- \\
        NONE \\
        ------------------------------ \\
        '''

        self.energy_file = 'oenergy.txt'
        self.forces_file = 'oforces.txt'

        with open(self.energy_file, 'w') as oenergy:
             oenergy.write("Step\tQM\t\tMM\t\tLink\t\tTotal\n")

        with open(self.forces_file, 'w') as oforces:
             oforces.write('')

    def oenergy_append(self, int_step_current, qmenergy, mmenergy, linkcorrenergy, total_energy):
            
            '''
            ------------------------------ \\
            EFFECT: \\
            --------------- \\
            XX \\
            ------------------------------ \\
            INPUT: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            RETURN: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            '''
            
            with open(self.energy_file, 'a+') as oenergy:
                oenergy.write(f"{int_step_current}\t{qmenergy:.6f}\t{mmenergy:.6f}\t{linkcorrenergy:.6f}\t{total_energy:.6f}\n")

    def oforces_append(self, int_step_current, total_force):
            
            '''
            ------------------------------ \\
            EFFECT: \\
            --------------- \\
            XX \\
            ------------------------------ \\
            INPUT: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            RETURN: \\
            --------------- \\
            NONE \\
            ------------------------------ \\
            '''
            
            with open(self.forces_file, 'a+') as oforce:
                lines = []  
                lines.append(f"Step {int_step_current}\n")
                
                for i in range(len(total_force)):
                    lines.append(f"{i + 1} {total_force[i][0]:.8f} {total_force[i][1]:.8f} {total_force[i][2]:.8f}\n")
                
                lines.append("\n")
                
                oforce.writelines(lines)
